### ISSUE TITLE
WP admin search defaults to solr

### ISSUE THREAD

**Issue by aayler** [pantheon-systems/solr-power#215] opened 2017-02-23 21:57 UTC
We recently upgraded to WP core 4.7.2 (from 4.6.1) and additionally upgraded solr-power to 1.0 from 0.6.

Following this, we're seeing that, without setting the "solr-integrate" parameter to true or using the "solr_allow_admin" filter hook, searches in our wp-admin (of custom post types, for instance) are using Sol, and returning thousands of results rather than the expect few ... any ideas on why this is happening and how to disable this?

And when we revert back to solr-power 0.6, the search returns to normal.

Thanks!

**Comment by ataylorme** [comment] 2017-02-23 22:12
> searches in our wp-admin (of custom post types, for instance) are using Sol, and returning thousands of results rather than the expect few

@aayler So the front-end of the site is returning results as expected and the issue is only in the admin?

Just want to make sure I try reproduce in the appropriate place.

![screen shot 2017-02-23 at 4 11 40 pm](https://cloud.githubusercontent.com/assets/2133004/23281430/e54fa42a-f9e2-11e6-8c62-42d46ba5711d.png)

**Comment by aayler** [comment] 2017-02-23 22:19
hi @ataylorme, i appreciate the prompt response!

unfortunately, the site search is off as well, in terms of the weights (boost) we've placed on search results. in other words, in the frontend, the results are correct but not in the desired display order.

and yes, i am referring to the search in the admin highlighted by the red arrow in your image.

(and we've reindexed the site, which is giving - as expected slightly different, likely new content, results, but the same behavior)

thanks again!

**Comment by ataylorme** [comment] 2017-02-23 22:23
> unfortunately, the site search is off as well, in terms of the weights (boost) we've placed on search results. in other words, in the frontend, the results are correct but not in the desired display order.

Can you open a separate issue for that? Including details on what type of content you are indexing, which boosts are being used, etc. will  be useful.

> and yes, i am referring to the search in the admin highlighted by the red arrow in your image.
Thanks for confirming. I'll try to reproduce.

Currently I would advise you to stick on `0.6` in production as we diagnose these issues. If you have another environment, like dev, you can work with me on these issues in that would be ideal.

**Comment by aayler** [comment] 2017-02-23 22:27
@ataylorme : thanks, will do re: site search issues.

we haven't pushed solr-power 1.0 to *live* yet, and in fact, we are working on a multidev testing env on pantheon ... what would be the best way to get in touch with you re: the site URL and credentials for you to review?

thanks again,

**Comment by ataylorme** [comment] 2017-02-23 23:17
> we haven't pushed solr-power 1.0 to live yet

Great - glad no possible bugs went live.

> we are working on a multidev testing env on pantheon

That's the ideal state :-). I don't like to assume anyone is on Pantheon, which is why I made a broad statement.

> what would be the best way to get in touch with you re: the site URL and credentials for you to review?

I'd like to keep troubleshooting public in GitHub issues if we can. Let's keep working here and if we get to a point where I need access to the site to debug we can chat directly. 

We have a Solr site setup with a lot of content and I'm able to debug/troubleshoot there. I was able to reproduce the issue of different post types showing up, from Solr, in the WordPress admin search.

![screen shot 2017-02-23 at 4 15 16 pm](https://cloud.githubusercontent.com/assets/2133004/23283095/d616674e-f9e9-11e6-9ec7-ce8a75573d83.png)

Good news is I found the issue. Bailing out on admin was commented out during work on the ajax widget since it uses `admin-ajax.php`.

I've submitted a pull request ([#216](https://github.com/pantheon-systems/solr-power/pull/216)) with a fix. @aayler if you can test the fix on you'll multidev and confirm we'll get it merged in and shipped in `1.1`, which should be coming in the next few weeks.

**Comment by aayler** [comment] 2017-02-24 15:24
hi @ataylorme, thanks for the link to the PR, will test on our multidev and report back.

thanks again!

**Comment by aayler** [comment] 2017-02-24 15:49
@ataylorme : the fix works for wp-admin searches; however, i noticed that the search for items in the media library is broken -- should https://github.com/pantheon-systems/solr-power/blob/54f5cd54f73a8013f6596ebdc9b3b45b2ab05856/includes/class-solrpower-wp-query.php#L73 also be uncommented, as that's targeting the AJAX requests?

thanks,

**Comment by ataylorme** [comment] 2017-02-24 16:00
@aayler The problem is that our search widget in `1.0` uses `admin-ajax.php` so we need to allow Solr in that scenario.

I've got meetings this morning but will take a look this afternoon.

**Comment by aayler** [comment] 2017-02-24 20:23
hi @ataylorme : regarding the front end issue, we located the issue (for us) = https://github.com/pantheon-systems/solr-power/blob/1.0.0/includes/class-solrpower-api.php#L359 this call dramatically changes the order of our search results ...

is there a way to override or reset/unset those "hard-coded" values, ie, 'post_title^25 post_content^50'?

and a quick question re: that line -- on = http://solarium.readthedocs.io/en/stable/queries/select-query/building-a-select-query/components/dismax-component/, the description of the boostFunctions method describes the string composed in the format:  "funcA(arg1,arg2)^1.2 funcB(arg3,arg4)^2.2". are post_title and post_content references to functions?

**Comment by ataylorme** [comment] 2017-02-24 21:26
Basically I disabled Solr in the admin or when admin ajax is being used by setting the `solr_allow_ajax` filter to false by default.

Then I apply filters before the widget runs and removes them after.

This has remove the issue searching custom post types and media but allowed the widget to still function in my testing.

@aayler can you test the updated PR on your multidev as well?

**Comment by aayler** [comment] 2017-02-24 22:03
@ataylorme 👍 , all looks good on my end.

thanks very much for your prompt and detailed support - very much appreciated!

**Comment by ataylorme** [comment] 2017-02-24 22:16
@aayler Awesome, glad to hear that. I'm going to open this back up until I can get a code review on the PR and we get it merged.

**Closed** 2017-03-01 17:10 UTC
Labels: bug
